server:
  port: 8080
spring:
  application:
    name: ZBJ-Ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-420282c972644ac7ad6de9f5775ae4d5
      chat:
        options:
          model: qwen3-max #Qwen/Qwen3-235B-A22B-Instruct-2507 # 要钱
      embedding:
        options:
          model: text-embedding-v4  # 向量维度
          dimensions: 1024 # qwen3-emb-4096
logging:
  level:
    org.springframework.ai: debug
    com.zbj.ai: debug
